languages:
  JavaScript: true

engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  fixme:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
    checks:
      import/no-unresolved:
        enabled: false
      import/extensions:
        enabled: false

ratings:
   paths:
   - "index.js"
   - "importCss.js"
   - "universalImport.js"

exclude_paths:
- "docs/"
- "dist/"
- "node_modules/"
- ".vscode/"
- ".eslintrc.js"
- "**/*.snap"
